### ISSUE TITLE
Project: current channel identification

### ISSUE THREAD

**Issue by PaulFarault** [adaltas/ece-2020-fall-webtech#10]
Not a bug but a "what's the best way to do it" question.

There appears to be redundancy in the way we can handle the current channel. 2 ways are present in the given project:
- Using [Context.js](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/a57e1922306c3f9a6410d96b33683254f56ba2c3/front-end/src/Context.js#L15), with `currentChannel, setCurrentChannel` which is not implemented
- Using params to pass an id from [Channels](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/front-end/src/Channels.js) to [Channel](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/front-end/src/Channel.js) and then args for the components

It seems to be cleaner to work with Context, is that a true statement ?

**Comment by wdavidw** [comment]
I didn't find any clear good practice feedbacks. Some folks plug the router behind the context. I choose to not use the context for the current channel but instead rely on the router params. It is easier at first and cleaner with the context. However, you have to handle the initialization of the current channel when some arrive directly on a channel route. For this reason, I finally choose the route approach and it plays well. The decision is up to you. Both have pros and cons.
