### ISSUE TITLE
Problem with Login with Github ("Loading tokens")

### ISSUE THREAD

**Issue by HN1997** [adaltas/ece-2020-fall-webtech#12]
Good morning sir,

I have an issue : When I connect with Github via dex (after "Grant Access"), the page loaded is "Loading tokens" and I don't really know why because it worked yesterday (and I managed to add a gravatar and I was able to log out). When I inspect the page (with "Loading tokens") I have an error (http://127.0.0.1:5556/dex/tokens, 400 bad request). By inspecting this error in the response, I have : error:"invalid_grant" and error_description:"Invalid code_verifier". 

Do you know how can I solve this please? 
![errordex](https://user-images.githubusercontent.com/63308850/101374542-929a9000-38ae-11eb-82ba-087a982ecc4f.png)

**Comment by wdavidw** [comment]
Try restarting Dex and using a new private windows in your browser. I bet it will work. I had similar issue when using different Dex server. The cover verifier in my cookies was not from the right Dex server.

**Comment by HN1997** [comment]
Unfortunately, I still have this error even after trying this.
I also tried to re-following all your steps that worked for the first time, but now it doesn't.

**Comment by wdavidw** [comment]
I had the error 2 times in the last few weeks. Every time, it was what is written, wrong code_verifier. Make sure you are generating a new cookie, you can use another web browser and the Dex config file I have provided to you. No error from the Dex console ?

**Comment by HN1997** [comment]
I tried to use Firefox and Google Chrome, plus in a private window, but nothing works. I have this issue in Chrome : 
![image](https://user-images.githubusercontent.com/63308850/101467126-384b0f00-3942-11eb-88b1-da62e74960b0.png)

And the Dex console never gives me any error, just a login successful:
![image](https://user-images.githubusercontent.com/63308850/101467356-7cd6aa80-3942-11eb-978b-adc3e3c10a7f.png)

Can the problem comes from Axios and proxy? I tried to play with it a little (but not in your project) : I created another project, I used Axios and in package.json adding a proxy to http://localhost:3001 (in the frontend) and used componentDidMount() function. Even if I didn't play with it in your project, maybe the proxy is still here? I tried to uninstall axios in your project and re-install it but it doesn't do anything.

**Comment by wdavidw** [comment]
I don't know what you call a proxy but there is no proxy. Also, using `componentDidMount` is only when you create react component as `class` which is not what I recommend you to do. All the component I provided you are written as `function` with hooks. Axios is fine, you do not need to remove it/modify it.

**Comment by tanb01** [comment]
Hi @HN1997 , you may have the same issue as me. Please refer to issue #13.
Make sure that your are going to **`http://127.0.0.1:3000`** and NOT `http://localhost:3000` thorughout your entire app (under the condition that you are indeed using the [**config.yaml**](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/dex-config/config.yaml) provided in the base project repository [ece-2020-fall-webtech-project](https://github.com/adaltas/ece-2020-fall-webtech-project) with the same `redirectURIs`.

**Comment by HN1997** [comment]
Thank you very much, going to http://127.0.0.1:3000 instead of http://localhost:3000 solved the problem!
