### ISSUE TITLE
Stuck on "Loading tokens" after logging in via GitHub

### ISSUE THREAD

**Issue by tanb01** [adaltas/ece-2020-fall-webtech#13]
Good morning Mr. Worms,

Since I am not receiving the same errors as the in the issue #12 , I have decided to create a new issue.
While using Firefox and Google Chrome, after logging in via GitHub and after the "Grant Access" menu, the react app logging page is stuck with the "Loading tokens" message.

At "http://127.0.0.1:5556/dex/token" I am receiving the following response:
**{"error":"invalid_client","error_description":"Invalid client credentials."}**

(I have not modified the [lab-correction](https://github.com/adaltas/ece-2020-fall-webtech/tree/master/courses/webtech/modules/06.oauth/lab-correction) folder in the 06.oauth folder). No errors appear in the Dex console. I redid the entire OAuth2 process by following your [post](https://www.adaltas.com/en/2020/11/20/oauth-microservices-public-app/), while using my own config file since I do not know where you have provided yours.

The errors and responses are shown in the screenshots below:

Response:
![image](https://user-images.githubusercontent.com/42753752/101418478-4a9b5d80-38ee-11eb-98a1-20d11a8cdd13.png)

Error in Firefox:
![image](https://user-images.githubusercontent.com/42753752/101417872-d0b6a480-38ec-11eb-8143-6ea03e936bba.png)

Error 1 in Google Chrome:
![image](https://user-images.githubusercontent.com/42753752/101419602-a7981300-38f0-11eb-93f8-18c0227305ba.png)

Error 2 in Google Chrome:
![image](https://user-images.githubusercontent.com/42753752/101417943-fa6fcb80-38ec-11eb-95cb-762a468aafc5.png)

**Comment by wdavidw** [comment]
> I do not know where you have provided yours

The file is in [`./dex-config/config.yaml`](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/dex-config/config.yaml). It is working, you must just adjust the GitHub `clientId` and `clientSecret` with yours.

**Comment by tanb01** [comment]
> > I do not know where you have provided yours
> 
> The file is in [`./dex-config/config.yaml`](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/dex-config/config.yaml). It is working, you must just adjust the GitHub `clientId` and `clientSecret` with yours.

Thank you @wdavidw or providing the config.yaml file!
I have adjusted it as mentioned above yet I am sadly still receiving the same errors...

**Comment by wdavidw** [comment]
You can not access `/dex/token` like in your screenshot above directly by entering it in your browser location bar. It must be a post request with the correct parameters like we do inside `Login.js`.

**Comment by tanb01** [comment]
The issue has been solved thanks to @wdavidw ,

The fix:
1. Ensure that you are using the correct base project provided here: [ece-2020-fall-webtech-project](https://github.com/adaltas/ece-2020-fall-webtech-project)
**Note: this is not the same repository as the course respository**

2. Follow the steps given in the [README.md](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/README.md) file of said repository.

3. After starting the back-end, front-end and dex server, the application must be opened at the same URL provided in the **config-private.yaml** file. This file being the following [config.yaml](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/dex-config/config.yaml) file but with your personal `clientID` and `clientSecret`!
So in our case, since we are using the previously mentioned config.yaml (now our config-private.yaml) file, our application **DOES NOT** start at `http://localhost:3000/` if not at **`http://127.0.0.1:3000`**.
Therefore, throughout the entire project YOU MUST GO TO THIS URL: **`http://127.0.0.1:3000`**.

Hope this helps you gals and guys out. Do not be shy to contact me about this issue. Good luck!
