### ISSUE TITLE
CookiesProvider

### ISSUE THREAD

**Issue by PaulFarault** [adaltas/ece-2020-fall-webtech#17]
I have noticed that `CookiesProvider` is placed inside of `ContextProvider`  in [index.js](https://github.com/adaltas/ece-2020-fall-webtech-project/blob/master/front-end/src/index.js). However, we are using cookies in our `Context`, how is it possible?
``` js 
ReactDOM.render(
  <React.StrictMode>
    <ContextProvider>
      <CookiesProvider>
        <ThemeProvider theme={theme}>
          <Router>
            <App />
          </Router>
        </ThemeProvider>
      </CookiesProvider>
    </ContextProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```

**Comment by wdavidw** [comment]
Good point but I don't have the answer. Inverting the two declarations seems appropriate.
