### ISSUE TITLE
How to loop with db requests?

### ISSUE THREAD

**Issue by PaulFarault** [adaltas/ece-2020-fall-webtech#19]
I want to recover several `channels` objects from the database from an array of `channelsIds`. To do that, I need to create a loop to make a request for each `channelId`.

``` js
getChannels: async (user) => {
    try {
      const channelsIds = user.channels
      channels = []
      await channelsIds.forEach(async channelId => {
        channels.push({
          id: channelId,
          name: JSON.parse(await db.get(`channels:${id}`)).name
        })
      })
      return channels
    } catch (e) {
      throw e
    }
  }
```

It returns an empty array. Which means that `db.get('channels:${id}')` is executed AFTER my return statement 😞 

I've tried several ways but nothing is working. I think that the problem comes from my use of `await`/`async`.
Would you be able to help me please?

**Comment by wdavidw** [comment]
I will go old style with `for`, a working example:

```js

const get_channel = (id) => {
  return new Promise( (accept) => {
    setTimeout( () => {
      accept({id: id})
    }, 100)
  })
}

( async () => {
  const ids = [1,2,3]
  const channels = []
  for(let i=0; i<ids.length; i++){
    const channel = await get_channel(ids[i])
    console.log(channel)
    channels.push(channel)
  }
  console.log(channels)
})()
```

**Comment by PaulFarault** [comment]
The answer was so obvious, it worked, thank you !!!
