### ISSUE TITLE
Github Project repository

### ISSUE THREAD

**Issue by miriambenallou** [adaltas/ece-2020-fall-webtech#20]
Dear Mr. Worms, 

I hope you're doing fine. I'm opening this issue regarding my group's repository for the project. I just discussed with other groups that informed me that they used the same repository as the one used for the labs. However, my collegue and I created another repo just for the project. Since that's what Mr. Kurdinov asked us to do, we supposed that we had to do the same thing for the Web-Tech project. Is it fine with you if we invite you to this new repo and send you all the info via e-mail ? Otherwise you won't see all the commits history etc... 

Could you please let us know if that suits you ? Otherwise, what should we do ? 

Thank you very much for your time and attention. 

Best regards, 
Miriam Benallou

**Comment by wdavidw** [comment]
I have been clear during the courses that you shall use the same repository as the one provided in September. In your case, it is https://github.com/miriambenallou/tech_web. Mr Kudinov give you the instructions that please him for his own course.

**Comment by wdavidw** [comment]
Note, in order to preserve your git history, you can simply force push into your lab repository. From your local project repository, it shall be something like (not tested):

```
# Remove the old remote repository
git remote remove origin
# Set the lab repository
git remote add origin https://github.com/miriambenallou/tech_web
# Force push the local git history to the new remote
git push -f -u origin master
```

**Comment by miriambenallou** [comment]
Thank you, we will do this
