### ISSUE TITLE
messages: fail to pass regex test

### ISSUE THREAD

**Issue by PaulFarault** [adaltas/ece-2020-fall-webtech#3]
The following test send me back an error

https://github.com/adaltas/ece-2020-fall-webtech/blob/403824a6c9407e023919dcce98b28a6b3d219fe8/courses/webtech/modules/03.storage/lab/test/messages.js#L37-L40

``` 
AssertionError: expected Array [ Object { creation: 1601027748590, content: 'Hello ECE' } ] to match Array [ Object { creation: /^d+$/, content: 'Hello ECE' } ]
not matched properties: '0' (Object { creation: 1601027748590, content: 'Hello ECE' })
``` 

The problem is that my results seem to match
``` 
Array [ Object { creation: 1601027748590, content: 'Hello ECE' } ]
Array [ Object { creation: /^d+$/       , content: 'Hello ECE' } ]
```

The error still remain when I modify the regex with `/^\d+$/` or `/^[0-9]+$/`

However, I'm able to pass the test when replacing the regex with tests numbers. I don't understand why it's failing with regex.

**Comment by wdavidw** [comment]
The types don't match, this is probably the reason, the regexp of the [Should.js `match`](https://shouldjs.github.io/#assertion-match) function works against strings and not integers. Refer to its documentation, we can pass a function. Try this from my [latest commit](https://github.com/adaltas/ece-2020-fall-webtech/commit/39d5e5338268bb6183049f67aa52d0b020771787):

```js
 messages.should.match([{ 
   creation: (it) => it.should.be.approximately(Date.now(), 1000),
   content: 'Hello ECE' 
 }]) 
```
