### ISSUE TITLE
Problem trying to validate messages' unit tests

### ISSUE THREAD

**Issue by SimonJ92** [adaltas/ece-2020-fall-webtech#4]
I have tried the following to store and handle the messages in order to validate the the first unit test in messages.js :

This first block is to store the data for channels and messages in db.js:
```js
/*[...]*/
const store =  {
  channels: {
    "messages": [{
    }]
  },
  users: {
  }
}
/*[...]*/
```

The following block of code is to list the messages of a specific channel, identified by idParent, in db.js
```js
module.exports = {
  channels: {

  /*[create, list, update and delete for the channels]*/

   listMessages: async(idParent) => {
      return Object.keys(store.channels[idParent].messages).map( (id) => {
        const message = clone(store.channels[idParent].messages[id])
        message.id = id
        return message
      })
    }
 }
}
```

The following block of code is to handle the route '/channels/:id/messages', to return all the messages on the channel identified by the id given in parameters, in apps.js
```js
app.get('/channels/:id/messages', async (req,res) => {
  const message = await db.channels.listMessages(req.params.id)
  res.json(message)
 })
})
```

The execution of the first unit test for messages currently ends in error :
```bash
UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object [...]
```

(The whole error message being very long, I didn't include it in its entirety)

I haven't found a solution for this problem yet. Could you give me an advice on what to do to solve it ?
I am unsure if I am stocking the data in the right way : Am I doing it wrong ?

**Comment by wdavidw** [comment]
This part is incorrect: `Object.keys(store.channels[idParent].messages).map`

`Object.keys` return the keys of an object literal, for example `store.channels` but messages is an array. You dont need it, simply call `store.channels[idParent].messages.map`

Note, if you don't include your stack trace, you can't expect much help.

**Comment by SimonJ92** [comment]
Thank you for you answer. I have corrected some parts of the code but encountered a new problem:

I simplified the first bit of code into the following :
```js
const store =  {
  channels: {
  },
  users: {
  }
}
```

I changed the second bit of code into the following:
```js
listMessages: async(idParent) => {
      return store.channels[idParent].messages.map( (message) => {
        return message
      })
    }
```

I added the declaration of an array of messages in the function for the creation of channels:
```js
create: async (channel) => { 
      if(!channel.name) throw Error('Invalid channel')
      const id = uuid()
      channel.messages = [] //initializing empty array of messages
      store.channels[id] = channel
      return merge(channel, {id: id})
    }
```
With the code arranged in this way, the first test was validated. However, when I modified the following line in the last bit of code to initialize any channel with 2 messages as follows: 
```js
channel.messages = [{text:"test1"},{text:"test2"}] //initializing a filled array of messages
```
the first test was also validated, even though it should only be validated if it is empty.

A log of the array of messages right before it is matched with an empty array at the end of the test gives the following:
```bash
[ { text: 'test1' }, { text: 'test2' } ]
```

Do you know what could lead to the test being falsely validated ?

**Comment by wdavidw** [comment]
Good catch, please refer to [the match documentation](https://shouldjs.github.io/#assertion-match), match work with the values of our messages and validate them. This is not what we want. Instead, we want to make sure messages is an empty array. We shall use `should.eql` or `should.deepEqual`.

**Comment by SimonJ92** [comment]
Thank you for you help ! It now works as expected.
Should we also use `should.eql` for the second test of messages.js ?

**Comment by SimonJ92** [comment]
Answer given in class : 
No : match is good for the second test because we want to test values.
