### ISSUE TITLE
Omitting the client_secret in the tutorial part2 step2 is not working

### ISSUE THREAD

**Issue by Lahkyk** [adaltas/ece-2020-fall-webtech#7]
Hello, 

I am blocked in the lab6 tutorial part2 step2 where we have to activate PKCE and enable CORS in Dex. When I attempt to repeat step1 and 2 by running the following command: 

npx openid-cli-usage code_grant \
  --client_id example-app \
  --token_endpoint http://127.0.0.1:5556/dex/token \
  --redirect_uri http://127.0.0.1:5555/callback \
  --code_verifier jVc-dP1YsCFp6px0XKFHBMtM5lwfp2inbb9xE8iv3y8 \
  --code ofupa4qe35oko4j7xzerrtyhp

I encounter the following error:

Required Option: the "client_secret" option must be provided

and I didn't succeed in resolving it.

**Comment by Lahkyk** [comment]
I didn't see but a previous issue (#5 ) already talked about this problem and resolved it.
But if someone is still looking for it, the answer is: remove all NPM local dir with "rm -rf ~/.npm" then "install npm" and update it (command given on the Terminal).

**Comment by wdavidw** [comment]
Seems to me like your problem was the Dex client configuration which defines a secret and which is not marked as public. Anyway, good you find a solution.
